image: Visual Studio 2019 Preview
skip_commits:
  message: /doco|Merge pull request.*/
install:
- cmd: choco install dotnetcore-sdk
before_build:
- ps: nuget restore
build:
  verbosity: minimal
configuration:
  - Release