<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Anotar.NLog.Fody" PrivateAssets="all" />
    <PackageReference Include="Anotar.Custom.Fody" PrivateAssets="all" />
    <PackageReference Include="Anotar.Splat.Fody" PrivateAssets="all" />
    <PackageReference Include="Anotar.CommonLogging.Fody" PrivateAssets="all" />
    <PackageReference Include="Anotar.Catel.Fody" PrivateAssets="all" />
    <PackageReference Include="Anotar.Serilog.Fody" PrivateAssets="all" />
    <PackageReference Include="AsyncErrorHandler.Fody" />
    <PackageReference Include="BasicFodyAddin.Fody" PrivateAssets="all" />
    <PackageReference Include="Caseless.Fody" PrivateAssets="all" />
    <PackageReference Include="Common.Logging.Core" />
    <PackageReference Include="Common.Logging" />
    <PackageReference Include="EmptyConstructor.Fody" PrivateAssets="all" />
    <PackageReference Include="Equatable.Fody" PrivateAssets="all" />
    <PackageReference Include="ExtraConstraints.Fody" PrivateAssets="all" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Fody" PrivateAssets="all" />
    <PackageReference Include="Ionad.Fody" PrivateAssets="all" />
    <PackageReference Include="MethodTimer.Fody" PrivateAssets="all" />
    <PackageReference Include="Catel.Core" />
    <PackageReference Include="NLog" />
    <PackageReference Include="PropertyChanged.Fody" PrivateAssets="all" />
    <PackageReference Include="PropertyChanging.Fody" PrivateAssets="all" />
    <PackageReference Include="Publicize.Fody" PrivateAssets="all" />
    <PackageReference Include="Obsolete.Fody" PrivateAssets="all" />
    <PackageReference Include="ModuleInit.Fody" PrivateAssets="all" />
    <PackageReference Include="InfoOf.Fody" />
    <PackageReference Include="Janitor.Fody" PrivateAssets="all" />
    <PackageReference Include="Splat" />
    <PackageReference Include="Resourcer.Fody" PrivateAssets="all" />
    <EmbeddedResource Include="Resource.txt" />
    <PackageReference Include="Serilog" />
    <PackageReference Include="Virtuosity.Fody" PrivateAssets="all" />
    <PackageReference Include="Visualize.Fody" PrivateAssets="all" />
    <PackageReference Include="Validar.Fody" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
  </ItemGroup>
</Project>
