<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net48;net8.0</TargetFrameworks>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Fody" PrivateAssets="all" />
    <PackageReference Include="NullGuard.Fody" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\ModuleInitializerAttribute.cs" Link="ModuleInitializerAttribute.cs" />
  </ItemGroup>
</Project>
