<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Costura.Fody" PrivateAssets="all" />
    <PackageReference Include="Fody" PrivateAssets="all" />
    <ProjectReference Include="..\CosturaAssemblyToReference\CosturaAssemblyToReference.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="System.Threading.Tasks" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="TUnit.Core" />
    <PackageReference Include="TUnit.Assertions" />
    <PackageReference Include="TUnit.Engine" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="..\ModuleInitializerAttribute.cs" Link="ModuleInitializerAttribute.cs" />
  </ItemGroup>
</Project>
